apiVersion: run.tanzu.vmware.com/v1alpha1  #TKGS API endpoint
kind: TanzuKubernetesCluster               #required parameter
metadata:
  name: tkgs-shared-services               #cluster name, user defined
  namespace: tgks-shared-services          #vsphere namespace
spec:
  distribution:
    version: v1.20                         #Resolves to latest TKR 1.19 version
  topology:
    controlPlane:
      count: 3                             #number of control plane nodes
      class: best-effort-medium            #vmclass for control plane nodes
      storageClass: tanzu                  #storageclass for control plane
    workers:
      count: 3                             #number of worker nodes
      class: best-effort-medium            #vmclass for worker nodes
      storageClass: tanzu                  #storageclass for worker nodes

