apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
      - name: hello
        image: harbor.bmath.nyc/hello/hello-world
      restartPolicy: Never
  backoffLimit: 4
